#!/bin/sh



if [[ "init" = $1 ]]; then

	python ~/.config/pgit/init.py

elif [[ "real" = $1 ]]; then 

        python ~/.config/pgit/main.py

elif [[ "ntag" = $1 ]]; then 
      
      python ~/.config/pgit/release.py
       
elif [[ "help" = $1 ]]; then 

    echo "
    [help] 
    pgit <command>

    commands

    init  : initialized git in a current folder 
    real :  activate real time upload
    ntag :  create a new release 
    update : download the last normal version 
    "
elif [[ "last" = $1 ]]; then 
     
    python ~/.config/pgit/last.py

elif [[ "upload" = $1 ]]; then 
    python ~/.config/pgit/upload.py
fi

